// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7U7F9VqWYKZp3gDYiN8iF4j9VftGoSN8',
    appId: '1:532557947352:web:71fd1e27f7fadea1a092ad',
    messagingSenderId: '532557947352',
    projectId: 'lokas-inventory-track',
    authDomain: 'lokas-inventory-track.firebaseapp.com',
    storageBucket: 'lokas-inventory-track.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4KsG5t7y8R1roS9MucTu97uCEafwgreg',
    appId: '1:532557947352:android:1d38f8cdfa427bf2a092ad',
    messagingSenderId: '532557947352',
    projectId: 'lokas-inventory-track',
    storageBucket: 'lokas-inventory-track.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCqUxXamzEBjNPtfEFB_gBYsxUfc2T2WI',
    appId: '1:532557947352:ios:3650d6297caa2aaca092ad',
    messagingSenderId: '532557947352',
    projectId: 'lokas-inventory-track',
    storageBucket: 'lokas-inventory-track.firebasestorage.app',
    iosBundleId: 'com.tubesabp.lokasTubesAbpMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCqUxXamzEBjNPtfEFB_gBYsxUfc2T2WI',
    appId: '1:532557947352:ios:3650d6297caa2aaca092ad',
    messagingSenderId: '532557947352',
    projectId: 'lokas-inventory-track',
    storageBucket: 'lokas-inventory-track.firebasestorage.app',
    iosBundleId: 'com.tubesabp.lokasTubesAbpMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7U7F9VqWYKZp3gDYiN8iF4j9VftGoSN8',
    appId: '1:532557947352:web:8998dcc0ba422683a092ad',
    messagingSenderId: '532557947352',
    projectId: 'lokas-inventory-track',
    authDomain: 'lokas-inventory-track.firebaseapp.com',
    storageBucket: 'lokas-inventory-track.firebasestorage.app',
  );
}
